draw_config:
  append_colon_to_layer_header: true
  dark_mode: auto
  arc_radius: 6.0
  arc_scale: 1.0
  combo_h: 26.0
  combo_w: 28.0
  inner_pad_h: 2.0
  inner_pad_w: 2.0
  key_h: 56.0
  key_rx: 6.0
  key_ry: 6.0
  key_w: 60.0
  line_spacing: 1.2
  outer_pad_h: 56.0
  outer_pad_w: 30.0
  small_pad: 2.0
  split_gap: 30.0
  glyphs: # mapping of glyph name to be used to svg definition
    vol_up: |
      <svg viewBox="2 3 34 33">
        <path style="stroke: white; fill: white;" d="M23.41,25.25a1,1,0,0,1-.54-1.85,6.21,6.21,0,0,0-.19-10.65,1,1,0,1,1,1-1.73,8.21,8.21,0,0,1,.24,14.06A1,1,0,0,1,23.41,25.25Z"/>
        <path style="stroke: white; fill: white;" d="M25.62,31.18a1,1,0,0,1-.45-1.89A12.44,12.44,0,0,0,25,6.89a1,1,0,1,1,.87-1.8,14.44,14.44,0,0,1,.24,26A1,1,0,0,1,25.62,31.18Z"/>
        <path style="stroke: white; fill: white;" d="M18.33,4,9.07,12h-6a1,1,0,0,0-1,1v9.92a1,1,0,0,0,1,1H8.88l9.46,8.24A1,1,0,0,0,20,31.43V4.72A1,1,0,0,0,18.33,4Z"/>
      </svg>
    bluetooth: |
      <svg viewBox="0 0 24 24">
      	<path style="stroke: white; fill: white;" d="M11,3H12L16.85,7.85L12.21,12.5L16.85,17.15L12,22H11V13.71L6.55,18.16L5.84,17.45L10.79,12.5L5.84,7.55L6.55,6.84L11,11.29V3M12,4.41V11.29L15.44,7.85L12,4.41M12,20.59L15.44,17.15L12,13.71V20.59Z" />
      </svg>
    vol_plus: |
      <svg viewBox="0 0 24 24">
        <path style="stroke: white; fill: white;" d="M2,9H6L10,5H12V20H10L6,16H2V9M3,15H6.41L10.41,19H11V6H10.41L6.41,10H3V15M17,16V13H14V12H17V9H18V12H21V13H18V16H17Z" />
      </svg>
    vol_minus: |
      <svg viewBox="0 0 24 24">
        <path style="stroke: white; fill: white;" d="M2,9H6L10,5H12V20H10L6,16H2V9M3,15H6.41L10.41,19H11V6H10.41L6.41,10H3V15M14,13V12H21V13H14Z" />
      </svg>
    vol_mute: |
      <svg viewBox="0 0 24 24">
        <path style="stroke: white; fill: white;" d="M2,9H6L10,5H12V20H10L6,16H2V9M3,15H6.41L10.41,19H11V6H10.41L6.41,10H3V15M13.96,15.33L16.79,12.5L13.96,9.67L14.67,8.96L17.5,11.79L20.33,8.96L21.04,9.67L18.21,12.5L21.04,15.33L20.33,16.04L17.5,13.21L14.67,16.04L13.96,15.33Z" />
      </svg>
    # bluetooth-off: |
    #  󰂲<svg viewBox="0 0 24 24">
    #     <path style="stroke: white; fill: white;" d="M13,5.83L14.88,7.71L13.28,9.31L14.69,10.72L17.71,7.7L12,2H11V7.03L13,9.03M5.41,4L4,5.41L10.59,12L5,17.59L6.41,19L11,14.41V22H12L16.29,17.71L18.59,20L20,18.59M13,18.17V14.41L14.88,16.29" />
    #   </svg>
  svg_style: |
    /* font and background color specifications */
    svg {
        font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 16px;
        font-kerning: normal;
        font-weight: bold;
        text-rendering: optimizeLegibility;
        fill: #24292e;
    }

    /* default key styling */
    rect {
        fill: #f6f8fa;
        stroke: #c9cccf;
        stroke-width: 1;
    }

    /* color accent for combo boxes */
    rect.combo {
        fill: #cdf;
    }

    /* color accent for held keys */
    rect.held, rect.combo.held {
        fill: #fdd;
    }

    /* color accent for ghost (optional) keys */
    rect.ghost, rect.combo.ghost {
        fill: #ddd;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
    }

    /* styling for layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        stroke: white;
        stroke-width: 2;
        paint-order: stroke;
    }

    /* styling for combo tap, and key hold/shifted label text */
    text.combo, text.hold, text.shifted {
        font-size: 11px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
    }

    /* styling for hold/shifted label text in combo box */
    text.combo.hold, text.combo.shifted {
        font-size: 8px;
    }

    /* styling for combo dendrons */
    path {
        stroke-width: 1;
        stroke: gray;
        fill: none;
    }
parse_config:
  zmk_remove_keycode_prefix: ["PT_"]
  zmk_additional_includes: ["../config/zmk-helpers"]
  assign_combos_to_layers: false
  preprocess: true
  qmk_keycode_map:
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    AT: '@'
    BACKSLASH: \
    BSLS: \
    CIRC: ^
    CIRCUMFLEX: ^
    COLN: ':'
    COLON: ':'
    COMM: ','
    COMMA: ','
    DLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTE: '"'
    DQT: '"'
    DQUO: '"'
    EQL: '='
    EQUAL: '='
    EXCLAIM: '!'
    EXLM: '!'
    GRAVE: '`'
    GRV: '`'
    GT: '>'
    HASH: '#'
    LABK: <
    LBRC: '['
    LCBR: '{'
    LEFT_ANGLE_BRACKET: <
    LEFT_BRACKET: '['
    LEFT_CURLY_BRACE: '{'
    LEFT_PAREN: (
    LPRN: (
    LT: <
    MINS: '-'
    MINUS: '-'
    'NO': ''
    NONUS_HASH: '#'
    NUHS: '#'
    PERC: '%'
    PERCENT: '%'
    PIPE: '|'
    PLUS: +
    QUES: '?'
    QUESTION: '?'
    QUOT: ''''
    QUOTE: ''''
    RABK: '>'
    RBRC: ']'
    RCBR: '}'
    RIGHT_ANGLE_BRACKET: '>'
    RIGHT_BRACKET: ']'
    RIGHT_CURLY_BRACE: '}'
    RIGHT_PAREN: )
    RPRN: )
    SCLN: ;
    SEMICOLON: ;
    SLASH: /
    SLSH: /
    TILD: '~'
    TILDE: '~'
    TRANSPARENT: ''
    TRNS: ''
    UNDERSCORE: _
    UNDS: _
    SPACE: ⎵
  raw_binding_map:
    '&mm_grescm': {t: '⎋', s: '` ~'}
    '&mm_shift_caps_word_l': {t: '⇧', s: ' ', h: ' '}
    '&mm_shift_caps_word_r': {t: '⇧', s: ' ', h: ' '}
    '&mm_bspc_del': {t: '⌫', s: '⌦'}
    '&mm_grescm_gui': {t: ⎋, h: ⌘, s: '~ `'}
    '&mm_spc_unds_layer': {t: '⎵', h: 'SYM', s: '_ -'}
    '&mm_plus_minus': {t: '+', s: '-'}
    '&mm_grave_caret': {t: '`', s: '^'}
    '&mm_bracket_r': {t: '(', s: ')'}
    '&mm_comma_semi_meh': {t: ',', s: ';', h: 'MEH'}
    '&mm_dot_colon': {t: '.', s: ':'}
    '&mm_none_undo': ''
    '&mm_left_word_cut': '↞'
    '&mm_up_save': '↑'
    '&mm_down_copy': '↓'
    '&mm_none_paste': ''
    '&mm_1_cut': '1'
    '&mm_2_copy': '2'
    '&mm_5_save': '5'
    '&swapper_cmd_tab': {t: '⌘↹'}
    '&td_at_email': {t: '@'}
    '&num_word': 'NUM'
    '&nav_word': 'NAV'
    '&caps_word_capslock': "Caps\nWord"
    '&caps_word': '⇪'
    '&bt BT_CLR': {t: '$$bluetooth$$', h: 'CLR'}
    '&magic_shift LSHFT 0': {t: '⇧', h: 'Sticky', s: 'Magic'}
    '&td2': {t: '/', s: '?', h: '¿'}
    # '&inverted_qmark_win': {t: '¿'}
    '&mmv MOVE_LEFT': ◀
    '&mmv MOVE_RIGHT': ►
    '&mmv MOVE_UP': ▲
    '&mmv MOVE_DOWN': ▼
    '&msc SCRL_LEFT': ◁
    '&msc SCRL_RIGHT': ▷
    '&msc SCRL_UP': △
    '&msc SCRL_DOWN': ▽
    '&sys_reset': 'RESET'
    '&smart_mouse': "Mouse\nLayer"
    '&bootloader': 'BOOT'
    '&mkp LCLK': 'L'
    '&mkp MCLK': 'M'
    '&mkp RCLK': 'R'
    '&td_shift_l': '⇧'
    '&td_shift_r': '⇧'
    '&td_nav_layer': {t: '⏎', h: 'NAV'}
    '&td_bt_clear': 'BT CLR'
    '&m_type_md_code_block': '```'
    # '&kp CAPSLOCK': "⇧\nLock"
    '&lt_num_word 4 0': {t: "Num\nWord", h: ''}
    '&ltog LGUI 5': {t: "Cancel\nNav", h: '⌘'}
    '&ltog LGUI 6': {t: "Cancel\nNum", h: '⌘'} 
    '&ltog LGUI 7': {t: "Cancel\nSym", h: '⌘'}
    '&ltog LGUI 8': {t: "Cancel\nFunc", h: '⌘'}
    '&ltog LGUI 9': {t: "Cancel\nAdjust", h: '⌘'}
    '&trans': {t: ' '}
  skip_binding_parsing: false
  zmk_keycode_map:
    BT_SEL: $$bluetooth$$
    BSPC: '⌫'
    DEL: '⌦'
    AMPERSAND: '&'
    AMPS: '&'
    APOS: .
    APOSTROPHE: <
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: {t: '\', s: '|'}
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: {t: ',', s: '<'}
    DLLR: $
    DOLLAR: $
    DOT: {t: '.', s: '>'}
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    ACUTE: {t: '´', s: '`'}
    GRAVE: {t: '`', s: '~'}
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NUBS: {t: '\', s: '|'}
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: {t: '.', s: '>'}
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: {t: ';', s: ':'}
    SEMICOLON:  {t: ';', s: ':'}
    SINGLE_QUOTE:  {t: '''', s: '"'}
    SLASH: {t: '/', s: '?'}
    SLASH: {t: '/', s: '?'}
    SQT: {t: '''', s: '"'}
    STAR: '*'
    TILDE: {t: '~', s: '^'}
    TILDE2: '~'
    UMLAUT: '¨'
    UNDER: _
    UNDERSCORE: _
    LCTRL: ⌃
    LALT: ⎇
    # LG: ⌘
    LGUI: ⌘
    # LS: ⇧
    LSHIFT: ⇧
    LSHFT: ⇧
    RCTRL: ⌃
    LEFT_CONTROL: ⌃
    LEFT_ALT: ⎇
    LEFT_GUI: ⌘
    LEFT_SHFT: ⇧
    RALT: ⎇
    RGUI: ⌘
    RSHFT: ⇧
    RIGHT_CONTROL: ⌃
    RIGHT_ALT: ⎇
    RIGHT_GUI: ⌘
    RSHIFT: ⇧
    RIGHT_SHFT: ⇧
    LEFT: ◀
    RIGHT: ►
    UP: ▲
    DOWN: ▼
    TAB: ↹
    SPACE: ⎵
    RET: '⏎'
    RETURN: '⏎'
    ESCAPE: '⎋'
    C_CEDILLA: 'Ç'
    C_PREV: '⏮'
    C_NEXT: '⏭'
    C_PLAY_PAUSE: '⏯'
    C_MUTE: $$vol_mute$$
    C_VOLUME_DOWN: $$vol_minus$$
    C_VOLUME_UP: $$vol_plus$$
    C_BRIGHTNESS_DEC: '☀↓'
    C_BRIGHTNESS_INC: '☀↑'
    LA(LEFT): ↞
    LA(RIGHT): ↠
    LG(LEFT): ⇤
    LG(RIGHT): ⇥
    'LS(LC(LG(LALT)))': 'HYPER'
    'RS(RC(RG(RALT)))': 'HYPER'
    'LC(LG(LALT))': 'MEH'
    'RC(RG(RALT))': 'MEH'
    'LG(Q)': '⌘Q'
    'LG(W)': '⌘W'
    'LG(GRAVE)': '⌘`'
    'LG(Z)': '⌘Z'
    'LG(X)': '⌘X'
    'LG(C)': '⌘C'
    'LG(V)': '⌘V'
    'LC(TAB)': '⌃↹'
    'LS(LC(TAB))': '⌃⇧↹'
    'LG(N0)': '⌘ 0'
    'LG(N1)': '⌘ 1'
    'LG(N2)': '⌘ 2'
    'LG(N3)': '⌘ 3'
    'LG(N4)': '⌘ 4'
    'LG(N5)': '⌘ 5'
    'LG(N6)': '⌘ 6'
    'LG(N7)': '⌘ 7'
    'LG(N8)': '⌘ 8'
    'LG(N9)': '⌘ 9'
    'LG(LS(N0))': '⌘ ⇧ 0'
    'LG(LS(N1))': '⌘ ⇧ 1'
    'LG(LS(N2))': '⌘ ⇧ 2'
    'LG(LS(N3))': '⌘ ⇧ 3'
    'LG(LS(N4))': '⌘ ⇧ 4'
    'LG(LS(N5))': '⌘ ⇧ 5'
    'LG(LS(N6))': '⌘ ⇧ 6'
    'LG(LS(N7))': '⌘ ⇧ 7'
    'LG(LS(N8))': '⌘ ⇧ 8'
    'LG(LS(N9))': '⌘ ⇧ 9'
    'LS(F1)': '⇧ F1'
    'LS(F2)': '⇧ F2'
    'LS(F3)': '⇧ F3'
    'LS(F4)': '⇧ F4'
    'LS(F5)': '⇧ F5'
    'LS(F6)': '⇧ F6'
    'LS(F7)': '⇧ F7'
    'LS(F8)': '⇧ F8'
    'LS(F9)': '⇧ F9'
    'LS(F10)': '⇧ F10'
    'LS(F11)': '⇧ F11'
    'LS(F12)': '⇧ F12'
  zmk_combos:
    combo_tog_nav_word: {'a': 'bottom', 'o': +0.05}
    combo_tog_num_word: {'a': 'bottom', 'o': +0.25}
    combo_return: {'a': 'bottom', 'o': 0.3}
    combo_nav_word: {'k': "Nav\nLayer"}
    combo_num_word: {'k': "Num\nLayer"}
    combo_sym_word: {'k': "Sym\nLayer"}
    combo_wm_word: {'k': "WM\nLayer"}
    combo_func_word: {'k': "Func\nLayer"}
    combo_capslock: {'k': "⇧\nLock"}
    combo_tog_mouse_keys_r: {'a': 'bottom', 'o': +2}
