manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joelspadin
      url-base: https://github.com/joelspadin
    - name: urob
      url-base: https://github.com/urob
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: gpeye
      url-base: https://github.com/GPeye
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: v0.3.0
    - name: zmk-locales
      remote: joelspadin
      revision: main
    - name: zmk-helpers
      remote: urob
      revision: v0.3.0
    - name: zmk-unicode
      remote: urob
      revision: v0.3.0
    - name: zmk-auto-layer
      remote: urob
      revision: v0.3.0
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
    - name: zmk-adaptive-key
      remote: urob
      revision: v0.3 # Should match ZMK release.
    - name: zmk-tri-state
      remote: urob
      revision: v0.3 # Should match ZMK release.
    - name: urchin-peripheral-animation
      remote: gpeye
      revision: main
  self:
    path: config
